baseURL = "https://lordsk.github.io/"
languageCode = "en-us"
title = "LordSk's blog"
theme = "hugo-nederburg-theme"
author = "LordSk"
disqusShortname = "lordskblog"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[params]
slogan = ""
description = "A blog for my various projects" # meta description
author = "LordSk"
authorLink = "https://lordsk.github.io/"
bio = [
""
]
copyright = [
"&copy; 2018 Thomas 'LordSk' Leroy",
"Nederburg Hugo Theme by [Appernetic](https://appernetic.io)."
]

# Nav links in the side bar
[[params.navlinks]]
name = "Home"
url = ""

[[params.navlinks]]
name = "CV"
url = "cv/cv_fr"

[[params.navlinks]]
name = "Contact"
url = "contact/contact"

[params.social]
twitter = "https://twitter.com/LordSk_"
github  = "https://github.com/LordSk"
