baseURL = "https://lordsk.github.io/"
languageCode = "en-us"
title = "LordSk's blog"
theme = "hugo-nederburg-theme"
author = "LordSk"

# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[params]
slogan = "Data is data"
description = "A blog for my various projects" # meta description
author = "LordSk"
authorLink = "https://lordsk.github.io/"
bio = [
""
]
copyright = [
"&copy; 2018 Thomas 'LordSk' Leroy",
"Nederburg Hugo Theme by [Appernetic](https://appernetic.io)."
]

# Nav links in the side bar
[[params.navlinks]]
name = "Home"
url = ""

[[params.navlinks]]
name = "About"
url = "about/"

[[params.navlinks]]
name = "Get in touch"
url = "contact/"

[params.social]
twitter = "https://twitter.com/LordSk_"
github  = "https://github.com/LordSk"
