baseURL = "https://lordsk.github.io/blog/"
languageCode = "en-us"
title = "Programming adventures"
author = "LordSk"
theme = "arabica"
disqusShortname = "lordskblog"
copyright = "Thomas Leroy"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5

[params]
    description = "A simple blog about my projects"
    dateFormatToUse = "02/01/2006"
    replaceGoogleFonts = "fonts.loli.net"
    twitter = "LordSk_"