baseURL = "https://lordsk.github.io/"
languageCode = "en-us"
title = "Programming adventures"
theme = "robust"
author = "LordSk"
disqusShortname = "lordskblog"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[params]
slogan = ""
description = "A blog for my various projects" # meta description
authorLink = "https://lordsk.github.io/"
bio = [
""
]
copyright = [
"&copy; 2018 Thomas 'LordSk' Leroy",
]

# Nav links in the side bar
[[params.navlinks]]
name = "Home"
url = ""

[[params.navlinks]]
name = "CV"
url = "cv/cv_fr"

[[params.navlinks]]
name = "Contact"
url = "contact/contact"

[params.social]
twitter = "https://twitter.com/LordSk_"
github  = "https://github.com/LordSk"

[params.author]
thumbnail = ""
name = "Thomas 'LordSk' Leroy"
description = ""
facebook = ""
twitter = "https://twitter.com/LordSk_"
github = "https://github.com/LordSk"
